### ISSUE TITLE
"CI" workflow does not run on PRs

### ISSUE THREAD

**Issue by ludovicsteinbach** [ansys/grantami-serverapi-openapi#101]
For example https://github.com/ansys/grantami-serverapi-openapi/pull/100.
Expected behavior:
- Push changes to pom file
- 'Generate client library' workflow runs, generates the client code and commits changes
- 'CI' workflow is triggered, as files in 'ansys-grantami-serverapi-openapi' have been modified. (<- does not happen)

May be related, but it seems that pushing another change to the pom file on an existing PR does not trigger a re-run of the 'Generate client library' workflow.

**Comment by Andy-Grigg** [comment]
I’m sure I’ve seen this working elsewhere, i.e. bomanalytics-openapi? You push a change to the pom or json definition, which triggers the regeneration of the code, and then the CI runs to bills and test the package.

I don’t have my laptop though, so it’s difficult to check to be sure.
