### ISSUE TITLE
Update swagger definition to support MI 2024 R1 and release

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/grantami-serverapi-openapi#94]
We will shortly have a final version of the Server API swagger definition file for 2024 R1.

Once we have this, we should build a new version of serverapi-openapi and release.

**Comment by Andy-Grigg** [comment]
We have hit the final RC, so I think we're good to do the final upgrade and to release this package.

**Comment by Andy-Grigg** [comment]
2.0.0rc0 of serverapi-openapi has been released.

**Comment by ludovicsteinbach** [comment]
2.0.0 has been released.
